"""SQLAlchemy Models — Package init. Import all models for Alembic discovery."""

from app.models.stored_file import StoredFile  # noqa: F401
from app.models.user import User  # noqa: F401
from app.models.client_profile import ClientProfile  # noqa: F401
from app.models.executive_assignment import ExecutiveClientAssignment  # noqa: F401
from app.models.manager_executive_assignment import ManagerExecutiveAssignment  # noqa: F401
from app.models.manager_client_assignment import ManagerClientAssignment  # noqa: F401
from app.models.master_document_type import MasterDocumentType  # noqa: F401
from app.models.master_doc_type_income_head import MasterDocTypeIncomeHead  # noqa: F401
from app.models.master_text_field_type import MasterTextFieldType  # noqa: F401
from app.models.master_text_field_type_income_head import MasterTextFieldTypeIncomeHead  # noqa: F401
from app.models.onboarding_form_field import OnboardingFormField  # noqa: F401
from app.models.filing import ITRFiling  # noqa: F401
from app.models.filing_document import FilingDocument  # noqa: F401
from app.models.filing_text_field import FilingTextField  # noqa: F401
from app.models.filing_computation import FilingComputation  # noqa: F401
from app.models.filing_completed_doc import FilingCompletedDoc  # noqa: F401
from app.models.filing_state_history import FilingStateHistory  # noqa: F401
from app.models.notification import Notification  # noqa: F401
from app.models.audit_log import AuditLog  # noqa: F401
from app.models.tag import Tag  # noqa: F401
from app.models.executive_tag import ExecutiveTag  # noqa: F401
from app.models.manager_tag import ManagerTag  # noqa: F401
from app.models.recovery_code import RecoveryCode  # noqa: F401
from app.models.client_income_heads import ClientIncomeHeads  # noqa: F401
from app.models.filing_feedback import FilingFeedback  # noqa: F401
from app.models.filing_other_doc import FilingOtherDoc  # noqa: F401
from app.models.internal_working_doc import InternalWorkingDoc  # noqa: F401
from app.models.viewer_completed_queue import ViewerCompletedQueue  # noqa: F401
