"""ITR Filing Platform — Enumeration types matching PostgreSQL ENUMs."""

import enum


class UserRole(str, enum.Enum):
    PARTNER = "PARTNER"
    EXECUTIVE = "EXECUTIVE"
    CLIENT = "CLIENT"
    DASHBOARD_USER = "DASHBOARD_USER"


class AccountStatus(str, enum.Enum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    DEACTIVATED = "DEACTIVATED"


class FilingStatus(str, enum.Enum):
    INITIATED = "INITIATED"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    PROCESSING = "PROCESSING"
    COMPUTATION = "COMPUTATION"
    FILING = "FILING"
    PAYMENT = "PAYMENT"
    COMPLETED = "COMPLETED"
    HALTED = "HALTED"


class DocumentStatus(str, enum.Enum):
    PENDING_UPLOAD = "PENDING_UPLOAD"
    UPLOADED = "UPLOADED"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"


class ComputationStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class CompletedDocType(str, enum.Enum):
    ITR_ACKNOWLEDGEMENT = "ITR_ACKNOWLEDGEMENT"
    INVOICE = "INVOICE"
    ITR_JSON = "ITR_JSON"
    ITR_FORM = "ITR_FORM"
    FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT"


class FormFieldType(str, enum.Enum):
    TEXT = "TEXT"
    NUMBER = "NUMBER"
    DATE = "DATE"
    DROPDOWN = "DROPDOWN"
    FILE = "FILE"


class AuditEventType(str, enum.Enum):
    ACCOUNT_REGISTERED = "ACCOUNT_REGISTERED"
    ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
    ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED"
    EXECUTIVE_CREATED = "EXECUTIVE_CREATED"
    EXECUTIVE_ASSIGNED = "EXECUTIVE_ASSIGNED"
    EXECUTIVE_UNASSIGNED = "EXECUTIVE_UNASSIGNED"
    FILING_INITIATED = "FILING_INITIATED"
    FILING_STATE_CHANGED = "FILING_STATE_CHANGED"
    FILING_HALTED = "FILING_HALTED"
    DOCUMENT_PLACEHOLDER_CREATED = "DOCUMENT_PLACEHOLDER_CREATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_APPROVED = "DOCUMENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_DOWNLOADED = "DOCUMENT_DOWNLOADED"
    COMPUTATION_UPLOADED = "COMPUTATION_UPLOADED"
    COMPUTATION_APPROVED = "COMPUTATION_APPROVED"
    COMPUTATION_REJECTED = "COMPUTATION_REJECTED"
    COMPUTATION_SUPERSEDED = "COMPUTATION_SUPERSEDED"
    ITR_FILED = "ITR_FILED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    INVOICE_UPLOADED = "INVOICE_UPLOADED"
    FORM_FIELD_ADDED = "FORM_FIELD_ADDED"
    FORM_FIELD_UPDATED = "FORM_FIELD_UPDATED"
    FORM_FIELD_REMOVED = "FORM_FIELD_REMOVED"
    MASTER_DOC_TYPE_ADDED = "MASTER_DOC_TYPE_ADDED"
    MASTER_DOC_TYPE_UPDATED = "MASTER_DOC_TYPE_UPDATED"
    MASTER_DOC_TYPE_REMOVED = "MASTER_DOC_TYPE_REMOVED"


class NotificationChannel(str, enum.Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    BOTH = "BOTH"


class TagType(str, enum.Enum):
    MANAGER = "MANAGER"
    LOCATION = "LOCATION"


class ActionItemType(str, enum.Enum):
    # Partner / Executive items
    VERIFY_CLIENT = "VERIFY_CLIENT"
    ASSIGN_EXECUTIVE = "ASSIGN_EXECUTIVE"
    SEND_DOCUMENT_CHECKLIST = "SEND_DOCUMENT_CHECKLIST"
    REVIEW_DOCUMENTS = "REVIEW_DOCUMENTS"
    MOVE_TO_COMPUTATION = "MOVE_TO_COMPUTATION"
    UPLOAD_COMPUTATION = "UPLOAD_COMPUTATION"
    MOVE_TO_FILING = "MOVE_TO_FILING"
    UPLOAD_COMPLETED_DOCS = "UPLOAD_COMPLETED_DOCS"
    MARK_PAYMENT_RECEIVED = "MARK_PAYMENT_RECEIVED"
    # Client items
    COMPLETE_ONBOARDING = "COMPLETE_ONBOARDING"
    UPLOAD_DOCUMENTS = "UPLOAD_DOCUMENTS"
    SUBMIT_DOCUMENTS = "SUBMIT_DOCUMENTS"
    REVIEW_COMPUTATION = "REVIEW_COMPUTATION"
    CONFIRM_TAX_PAID = "CONFIRM_TAX_PAID"


class ActionItemPriority(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


# Valid state transitions for the filing state machine
VALID_FILING_TRANSITIONS: dict[FilingStatus, list[FilingStatus]] = {
    FilingStatus.INITIATED: [FilingStatus.DOCUMENT_UPLOAD, FilingStatus.HALTED],
    FilingStatus.DOCUMENT_UPLOAD: [FilingStatus.PROCESSING, FilingStatus.HALTED],
    FilingStatus.PROCESSING: [FilingStatus.DOCUMENT_UPLOAD, FilingStatus.COMPUTATION, FilingStatus.HALTED],
    FilingStatus.COMPUTATION: [FilingStatus.PROCESSING, FilingStatus.FILING, FilingStatus.HALTED],
    FilingStatus.FILING: [FilingStatus.PAYMENT, FilingStatus.HALTED],
    FilingStatus.PAYMENT: [FilingStatus.COMPLETED, FilingStatus.HALTED],
    FilingStatus.HALTED: [
        FilingStatus.INITIATED,
        FilingStatus.DOCUMENT_UPLOAD,
        FilingStatus.PROCESSING,
        FilingStatus.COMPUTATION,
        FilingStatus.FILING,
        FilingStatus.PAYMENT,
    ],
}
